I PUT MY WRAPPERS FOR 3 APIs HERE:

In [20]:
import requests
import json
import pandas as pd
from functools import reduce

def recipe_search(ingredient, app_id = '06d214b7', app_key = 'aa13fd9849c50147db6825a20c992dac'):
    '''query for recipe search api'''
    result = requests.get('https://api.edamam.com/search?q={}&app_id={}&app_key={}'.format(ingredient, app_id, app_key))
    data = result.json()
    return data#['hits']
#print(json.dumps(recipe_search('1%20butternut%20squash'), indent=4))

def food_database(ingredient, app_id = 'ff645722', app_key = 'bb33b6fafc32f853d2310b2100ff7540'):
    '''query for food database api'''
    result = requests.get('https://api.edamam.com/api/food-database/v2/parser?ingr={}&app_id={}&app_key={}'.format(ingredient, app_id, app_key))
    data = result.json()
    return data#['hits']

def nutrition_details(ingredient, app_id = '9a1286ed', app_key = 'fa2b2b31f4a34a334a4ef84291dd8f59 '):
    '''query for nutrition details api'''
    result = requests.get('https://api.edamam.com/api/nutrition-data?ingr={}&app_id={}&app_key={}'.format(ingredient, app_id, app_key))
    data = result.json()
    return data#['hits']

In [21]:
class Product:
    def __init__(self, name):
        self.name = name
        self.nutrients = nutrition_details(name)

    def get_name(self):
        return self.name

    def get_nutrients(self):
        '''return pd.DataFrame of nutrients'''
        return pd.DataFrame.from_records(self.nutrients['totalNutrients']).T.reset_index()

    def get_weight(self):
        '''return weight in grams'''
        return self.nutrients["totalWeight"]

    def get_calories(self):
        '''return pd.DataFrame of calories and its sources'''
        d = {k: v['quantity'] for k, v in self.nutrients['totalNutrientsKCal'].items()}
        return pd.DataFrame(d, index=['kcal']).T.reset_index()

    def get_foodmatch(self):
        return self.nutrients['ingredients'][0]['parsed'][0]['foodMatch']

    def get_food(self):
        return self.nutrients['ingredients'][0]['parsed'][0]['food']

product = Product('200g chicken fillet')

In [22]:
class Recipe:
    def __init__(self, recipe):
        self.ingredients = recipe.split('\n')

    def set_edamam_info(self):
        product_collection = [Product(i) for i in self.ingredients]

        product_name = [product.get_name() for product in product_collection]
        product_food = [product.get_food() for product in product_collection]
        product_foodmatch = [product.get_foodmatch() for product in product_collection]
        product_weight = [product.get_weight() for product in product_collection]

        product_nutrients = [product.get_nutrients() for product in product_collection]
        product_calories = [product.get_calories() for product in product_collection]

        self._calories_df = pd.concat([x.rename(columns={'kcal': name}).set_index('index')
                                      for name, x in zip(product_name, product_calories)],
                                     axis=1).T.reset_index().rename(columns={'index': 'ingredient'})
        #self._calories_df = self._calories_df.set_index('index')
        self._info_df = pd.DataFrame({'ingredient': product_name, 'food': product_food,
                                    'foodmatch': product_foodmatch, 'weight': product_weight})

        self._nutrients_df = reduce(lambda df1, df2: df1.merge(df2, left_on='index', right_on='index', how='outer'),
                                   [df[['index', 'quantity']].rename(columns={'quantity': n}) for df, n in zip(product_nutrients,product_name)])

        self._nutrients_df_units = reduce(lambda df1, df2: df1.merge(df2, left_on='index', right_on='index', how='outer'),
                                   [df[['index', 'unit']].rename(columns={'unit': n}) for df, n in zip(product_nutrients,product_name)])

In [23]:
r = \
'''1 spoon butter ghee
250g butternut squash
1 red onion
5g curry
1 teaspoon ground hot peppers
200g chicken fillet
200g boiled chickpeas
150g canned tomatoes
150ml coconut milk
100g spinach'''
recipe = Recipe(r)
recipe.set_edamam_info()

In [16]:
recipe = Recipe('100g baked potatoes')
recipe.set_edamam_info()

In [30]:
recipe._calories_df

index,ingredient,ENERC_KCAL,PROCNT_KCAL,FAT_KCAL,CHOCDF_KCAL
0,1 spoon butter ghee,112,0,112,0
1,250g butternut squash,113,9,2,102
2,1 red onion,50,5,1,44
3,5g curry,16,2,5,9
4,1 teaspoon ground hot peppers,1,0,0,1
5,200g chicken fillet,430,152,278,0
6,200g boiled chickpeas,757,160,106,491
7,150g canned tomatoes,24,4,3,17
8,150ml coconut milk,282,11,256,15
9,100g spinach,23,9,3,11

In [31]:
recipe._info_df

,ingredient,food,foodmatch,weight
0,1 spoon butter ghee,ghee,ghee,12.800000
1,250g butternut squash,butternut squash,butternut squash,250.000000
2,1 red onion,onions,red onion,125.000000
3,5g curry,curry powder,curry,5.000000
4,1 teaspoon ground hot peppers,red chili,hot peppers,3.125000
5,200g chicken fillet,chicken,chicken,200.000000
6,200g boiled chickpeas,chickpeas,chickpeas,200.000000
7,150g canned tomatoes,canned ripe red tomatoes,canned tomatoes,150.000000
8,150ml coconut milk,coconut milk,coconut milk,143.286921
9,100g spinach,spinach,spinach,100.000000

In [35]:
recipe._nutrients_df

,index,1 spoon butter ghee,250g butternut squash,1 red onion,5g curry,1 teaspoon ground hot peppers,200g chicken fillet,200g boiled chickpeas,150g canned tomatoes,150ml coconut milk,100g spinach
0,CA,0.512,120.0,28.75,26.25,0.4375,22.0,114.0,49.5,25.791646,99.0
1,CHOCDF,0.0,29.225,11.675,2.7915,0.275313,0.0,125.9,5.205,4.026362,3.63
2,CHOLE,32.768,0.0,0.0,0.0,0.0,150.0,0.0,0.0,0.0,0.0
3,ENERC_KCAL,112.128,112.5,50.0,16.25,1.25,430.0,756.0,24.0,282.275235,23.0
4,FAMS,3.677696,0.0175,0.01625,0.4391,0.00075,12.48,2.754,0.06,1.299612,0.01
5,FAPU,0.472832,0.105,0.02125,0.1528,0.007469,6.46,5.462,0.1515,0.333859,0.165
6,FASAT,7.926272,0.0525,0.0525,0.0824,0.001313,8.62,1.206,0.051,27.102721,0.063
7,FAT,12.73344,0.25,0.125,0.7005,0.01375,30.12,12.08,0.375,30.5631,0.39
8,FE,0.0,1.75,0.2625,0.955,0.032188,1.8,8.62,0.855,4.728468,2.71
9,FIBTG,0.0,5.0,2.125,2.66,0.046875,0.0,24.4,2.85,NaN,2.2
10,FOLAC,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11,FOLDFE,0.0,67.5,23.75,2.8,0.71875,12.0,1114.0,12.0,20.060169,194.0
12,FOLFD,0.0,67.5,23.75,2.8,0.71875,12.0,1114.0,12.0,20.060169,194.0
13,K,0.64,880.0,182.5,58.5,10.0625,378.0,1436.0,286.5,315.231227,558.0
14,MG,0.0,85.0,12.5,12.75,0.71875,40.0,158.0,15.0,65.911984,79.0
15,NA,0.256,10.0,5.0,2.6,0.28125,140.0,48.0,172.5,18.6273,79.0
16,NIA,0.000384,3.0,0.145,0.163,0.038875,13.602,3.082,1.068,0.912738,0.724
17,P,0.384,82.5,36.25,18.35,1.34375,294.0,504.0,25.5,137.555444,49.0
18,PROCNT,0.03584,2.5,1.375,0.7145,0.058438,37.2,40.94,1.185,2.894396,2.86
19,RIBF,0.00064,0.05,0.03375,0.01,0.002688,0.24,0.424,0.0825,0.0,0.189
20,SUGAR,0.0,5.5,5.3,0.138,0.165625,0.0,21.4,3.825,NaN,0.42
21,THIA,0.000128,0.25,0.0575,0.0088,0.00225,0.12,0.954,0.8625,0.031523,0.078
22,TOCPHA,0.3584,3.6,0.025,1.262,0.021563,0.6,1.64,0.885,NaN,2.03
23,VITA_RAE,107.52,1330.0,0.0,0.05,1.5,82.0,6.0,30.0,0.0,469.0
24,VITB12,0.00128,0.0,0.0,0.0,0.0,0.62,0.0,0.0,0.0,0.0
25,VITB6A,0.000128,0.385,0.15,0.00525,0.015813,0.7,1.07,0.1665,0.04012,0.195
26,VITC,0.0,52.5,9.25,0.035,4.490625,3.2,8.0,18.9,1.432869,28.1
27,VITD,0.2304,0.0,0.0,0.0,0.0,0.4,0.0,0.0,0.0,0.0
28,VITK1,1.1008,2.75,0.5,4.99,0.4375,3.0,18.0,3.9,NaN,482.9
29,WATER,0.03072,216.025,111.3875,0.44,2.750625,131.98,15.36,142.125,104.427508,91.4
30,ZN,0.00128,0.375,0.2125,0.235,0.008125,2.62,5.52,0.18,0.802407,0.53
31,CHOCDF.net,NaN,24.225,9.55,0.1315,0.228438,NaN,101.5,2.355,4.026362,1.43
32,FATRN,NaN,NaN,NaN,0.0,NaN,0.194,NaN,NaN,NaN,NaN

In [36]:
recipe._nutrients_df_units

,index,1 spoon butter ghee,250g butternut squash,1 red onion,5g curry,1 teaspoon ground hot peppers,200g chicken fillet,200g boiled chickpeas,150g canned tomatoes,150ml coconut milk,100g spinach
0,CA,mg,mg,mg,mg,mg,mg,mg,mg,mg,mg
1,CHOCDF,g,g,g,g,g,g,g,g,g,g
2,CHOLE,mg,mg,mg,mg,mg,mg,mg,mg,mg,mg
3,ENERC_KCAL,kcal,kcal,kcal,kcal,kcal,kcal,kcal,kcal,kcal,kcal
4,FAMS,g,g,g,g,g,g,g,g,g,g
5,FAPU,g,g,g,g,g,g,g,g,g,g
6,FASAT,g,g,g,g,g,g,g,g,g,g
7,FAT,g,g,g,g,g,g,g,g,g,g
8,FE,mg,mg,mg,mg,mg,mg,mg,mg,mg,mg
9,FIBTG,g,g,g,g,g,g,g,g,NaN,g
10,FOLAC,µg,µg,µg,µg,µg,µg,µg,µg,µg,µg
11,FOLDFE,µg,µg,µg,µg,µg,µg,µg,µg,µg,µg
12,FOLFD,µg,µg,µg,µg,µg,µg,µg,µg,µg,µg
13,K,mg,mg,mg,mg,mg,mg,mg,mg,mg,mg
14,MG,mg,mg,mg,mg,mg,mg,mg,mg,mg,mg
15,NA,mg,mg,mg,mg,mg,mg,mg,mg,mg,mg
16,NIA,mg,mg,mg,mg,mg,mg,mg,mg,mg,mg
17,P,mg,mg,mg,mg,mg,mg,mg,mg,mg,mg
18,PROCNT,g,g,g,g,g,g,g,g,g,g
19,RIBF,mg,mg,mg,mg,mg,mg,mg,mg,mg,mg
20,SUGAR,g,g,g,g,g,g,g,g,NaN,g
21,THIA,mg,mg,mg,mg,mg,mg,mg,mg,mg,mg
22,TOCPHA,mg,mg,mg,mg,mg,mg,mg,mg,NaN,mg
23,VITA_RAE,µg,µg,µg,µg,µg,µg,µg,µg,µg,µg
24,VITB12,µg,µg,µg,µg,µg,µg,µg,µg,µg,µg
25,VITB6A,mg,mg,mg,mg,mg,mg,mg,mg,mg,mg
26,VITC,mg,mg,mg,mg,mg,mg,mg,mg,mg,mg
27,VITD,µg,µg,µg,µg,µg,µg,µg,µg,µg,µg
28,VITK1,µg,µg,µg,µg,µg,µg,µg,µg,NaN,µg
29,WATER,g,g,g,g,g,g,g,g,g,g
30,ZN,mg,mg,mg,mg,mg,mg,mg,mg,mg,mg
31,CHOCDF.net,NaN,g,g,g,g,NaN,g,g,g,g
32,FATRN,NaN,NaN,NaN,g,NaN,g,NaN,NaN,NaN,NaN

In [8]:
"""
with open('ingredient_prices.json', 'r') as f:
    shop = json.load(f)["ingredients"]
shop"""
recipe._calories_df
#recipe._info_df

#r

index,ingredient,ENERC_KCAL,PROCNT_KCAL,FAT_KCAL,CHOCDF_KCAL
0,1 spoon butter ghee,112,0,112,0
1,250g butternut squash,113,9,2,102
2,1 red onion,50,5,1,44
3,5g curry,16,2,5,9
4,1 teaspoon ground hot peppers,1,0,0,1
5,200g chicken fillet,430,152,278,0
6,200g boiled chickpeas,757,160,106,491
7,150g canned tomatoes,24,4,3,17
8,150ml coconut milk,282,11,256,15
9,100g spinach,23,9,3,11

In [189]:
def get_recipe_prices(recipe):
    '''get full df of specific RECIPE prices'''
    with open('ingredient_prices.json', 'r') as f:
        shop = json.load(f)["ingredients"]
        _shop_data = [nutrition_details(f'{x["amount"]}{x["units"]} {x["name"]}') for x in shop]
        shop_set_weights = {x['ingredients'][0]['parsed'][0]['food']: x["totalWeight"] for x in _shop_data}
        shop_set_prices = {x['ingredients'][0]['parsed'][0]['food']: y['price'] for x, y in zip(_shop_data, shop)}

        recipe_set = recipe.split('\n')
        _recipe_data = [nutrition_details(x) for x in recipe_set]
        recipe_set_weights = {x['ingredients'][0]['parsed'][0]['food']: x["totalWeight"] for x in _recipe_data}
        recipe_set_prices = {
            x: shop_set_prices[x] * recipe_set_weights[x] / shop_set_weights[x] if x in shop_set_weights else None for x
            in recipe_set_weights}

    return pd.DataFrame(recipe_set_prices, index=[0])

         index  unit
0           CA    mg
1       CHOCDF     g
2        CHOLE    mg
3   ENERC_KCAL  kcal
4         FAMS     g
5         FAPU     g
6        FASAT     g
7          FAT     g
8           FE    mg
9        FIBTG     g
10       FOLAC    µg
11      FOLDFE    µg
12       FOLFD    µg
13           K    mg
14          MG    mg
15          NA    mg
16         NIA    mg
17           P    mg
18      PROCNT     g
19        RIBF    mg
20       SUGAR     g
21        THIA    mg
22      TOCPHA    mg
23    VITA_RAE    µg
24      VITB12    µg
25      VITB6A    mg
26        VITC    mg
27        VITD    µg
28       VITK1    µg
29       WATER     g
30          ZN    mg

In [230]:
#recipe.calories_df
#recipe.info_df
#recipe.nutrients_df
#recipe.nutrients_df_units
testable = Product('200g chicken fillet')
testable.get_foodmatch()

'chicken'

In [212]:
x['name'], pr.get_food(), pr.get_foodmatch(), pr.get_weight()

names = [x['name'] for x in ]
_shop_data = [nutrition_details(f'{x["amount"]}{x["units"]} {x["name"]}') for x in shop]
shop_set_weights = {x['ingredients'][0]['parsed'][0]['food']: x["totalWeight"] for x in _shop_data}
shop_set_prices = {x['ingredients'][0]['parsed'][0]['food']: y['price'] for x, y in zip(_shop_data, shop)}

('butternut squash', 'butternut squash', 'butternut squash', 1000.0)

In [228]:
shop_df = pd.DataFrame(shop)
shop_df['full_name'] = shop_df.apply(lambda x: f'{x["amount"]}{x["units"]} {x["name"]}', axis=1)
shop_df #shop_info

,name,amount,units,price,href,full_name
0,butternut squash,1000,g,1.79,https://barbora.lt/produktai/sviestiniai-moliu...,1000g butternut squash
1,red onion,1000,g,0.99,https://barbora.lt/produktai/rausvieji-svoguna...,1000g red onion
2,curry,40,g,0.59,https://barbora.lt/produktai/karis-tasty-home-...,40g curry
3,ground hot peppers,160,g,1.29,https://barbora.lt/produktai/maltos-aitriosios...,160g ground hot peppers
4,chicken fillet,400,g,2.99,https://barbora.lt/produktai/visciuku-broileri...,400g chicken fillet
5,boiled chickpeas,400,g,1.29,https://barbora.lt/produktai/avinzirniai-400-g,400g boiled chickpeas
6,canned tomatoes,400,g,0.79,https://barbora.lt/produktai/konservuoti-smulk...,400g canned tomatoes
7,coconut milk,400,ml,1.39,https://barbora.lt/produktai/ekologiskas-kokos...,400ml coconut milk
8,spinach,200,g,1.89,https://barbora.lt/produktai/mazieji-spinatai-...,200g spinach
9,butter ghee,500,g,10.69,https://barbora.lt/produktai/lydytas-sviestas-...,500g butter ghee

0     1000g butternut squash
1            1000g red onion
2                  40g curry
3    160g ground hot peppers
4        400g chicken fillet
5      400g boiled chickpeas
6       400g canned tomatoes
7         400ml coconut milk
8               200g spinach
9           500g butter ghee
dtype: object

In [225]:
shop_df

,name,amount,units,price,href
0,butternut squash,1000,g,1.79,https://barbora.lt/produktai/sviestiniai-moliu...
1,red onion,1000,g,0.99,https://barbora.lt/produktai/rausvieji-svoguna...
2,curry,40,g,0.59,https://barbora.lt/produktai/karis-tasty-home-...
3,ground hot peppers,160,g,1.29,https://barbora.lt/produktai/maltos-aitriosios...
4,chicken fillet,400,g,2.99,https://barbora.lt/produktai/visciuku-broileri...
5,boiled chickpeas,400,g,1.29,https://barbora.lt/produktai/avinzirniai-400-g
6,canned tomatoes,400,g,0.79,https://barbora.lt/produktai/konservuoti-smulk...
7,coconut milk,400,ml,1.39,https://barbora.lt/produktai/ekologiskas-kokos...
8,spinach,200,g,1.89,https://barbora.lt/produktai/mazieji-spinatai-...
9,butter ghee,500,g,10.69,https://barbora.lt/produktai/lydytas-sviestas-...